### ISSUE TITLE
Error running simpleaf quant within singularity container

### ISSUE THREAD

**Issue by HelenLindsay** [COMBINE-lab/usefulaf#8] opened 2022-10-18 13:20 UTC
Hello,

I'm trying to run simpleaf quant from within the singularity container on a Ubuntu server, and I get an error generating the permit list. 

This is the last few lines of the captured standard output:

```console
gpl:
command: /opt/conda/bin/time -v -o /workdir/quants/logdir/gpl.time alevin-fry generate-permit-list -u /workdir/.afhome/plist/10x_v3_permit.txt -d fw -i /workdir/quants/alevin_map -o /workdir/quants/gpl/ |& stdbuf -oL tr '\r' '\n' > /workdir/quants/logdir/gpl.log
```

This is the output of gpl.log:

 ```console
 thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `16`,
 right: `7`: found barcodes of different lenghts 16 and 7', libradicl/src/cellfilter.rs:203:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 ```
 However, I installed a local version of alevin-fry from the bioconda channel and was able to successfully step through the simpleaf_quant function in the simpleaf script from generating the permit list onwards, using the .rad files and splici index I generated from within the singularity container and the 10x_v3_permit.txt downloaded from the link in get_10x_permit_lists.sh.
 
 My local version of alevin-fry is 0.4.1 and the version in the singularity container is 0.4.0.
 
 Do you have any idea why I get an error using the singularity container?

**Comment by rob-p** [comment] 2022-10-18 14:25
Hi @HelenLindsay,

  I am not sure why you might be seeing this issue.  It's a bit hard to say without the data (is that publicly available?).

  Regardless, `alevin-fry` 0.4.0 and 0.4.1 are both quite old now, and it's certainly time that we update the docker image and singularity container (are you using the latest one?).  @DongzeHE and I will try to push out the update ASAP and ping back here when its done.

Best,
Rob

**Comment by rob-p** [comment] 2022-10-18 20:24
Hi @HelenLindsay,

  Could you please pull down the latest docker container into singularity and see if the issue persists for you?

```
singularity pull docker://combinelab/usefulaf:latest
```

I should also note that we are in the process of moving away the assorted collection of scripts that constitute `simpleaf` as implemented here, and instead are moving to a dedicated and more capable workflow wrapper (https://github.com/COMBINE-lab/simpleaf).  We will also update the README here once there is also a container for that.

**Comment by HelenLindsay** [comment] 2022-10-19 12:56
Hi @rob-p 

Thanks for the info.  I think I was running the singularity container from the umd.box link here:

https://combine-lab.github.io/alevin-fry-tutorials/2021/quickstart-usefulaf-singularity/

I hadn't even thought to check the version as I only installed alevin-fry from bioconda yesterday, but there's evidently something wrong with my conda configuration.  

I've pulled the latest docker into singularity and will run my analysis again and let you know once it's finished.

**Comment by HelenLindsay** [comment] 2022-10-21 12:22
Yes, I get the same error using the latest singularity container.  Here's a subset of my fastq files, this is enough to generate the error on the Ubuntu server I'm using: [fastq_subset.tar.gz](https://github.com/COMBINE-lab/usefulaf/files/9838835/fastq_subset.tar.gz)

I'm happy if you want to close this issue as I've finished the quantification on my local machine and this version of the simpleaf pipeline will be retired.

**Comment by rob-p** [comment] 2022-10-21 13:13
Thanks so much for sharing the data. We will see if we can reproduce it on our end, and will post the result here either way to close the issue once we've looked at it.  I'm glad you were able to get everything to run locally.

In the mean time, I've been able to get a nice small docker (hence singularity) image wrapping the improved workflow tool [simpleaf](https://github.com/COMBINE-lab/simpleaf), and we will update the information and pointers in this repo once that is pushed.  Since you got things working locally natively, I don't want to mess with your workflow — but since you can install things via bioconda, you might want to check out [simpleaf](https://github.com/COMBINE-lab/simpleaf) itself to simplify your processing (e.g. running fewer commands to get to your end point).

Thanks again for the report and all the feedback!

**Comment by rob-p** [comment] 2022-10-21 15:29
Thanks again @HelenLindsay! I've updated the readme on this repo to point to the relevant places, and we have again updated the latest Docker image to be based around the new and improved [`simpleaf`](https://github.com/COMBINE-lab/simpleaf) wrapper.  The updated tutorial is [here](https://combine-lab.github.io/alevin-fry-tutorials/2021/quickstart-usefulaf-singularity/).  I'm guessing it will avoid the above error since building the splici reference no longer requires invoking any R code at all, so that the entire indexing and quantification process happens entirely in Python/C++/Rust.

Let us know if you have any more questions or run into any more issues!

**Closed as completed by rob-p** 2022-10-21 15:29 UTC
